### ISSUE TITLE
I have not received a message from the Telegram bot for more than 10 minutes.

### ISSUE THREAD

**Issue by TokenStyle** [enovikov11/political-quiz-bot#4]
In the attached picture, you can see that the message from the Telegram bot has not been received for more than 10 minutes. How can this problem be solved?

![image](https://user-images.githubusercontent.com/56667933/104847729-1616ba80-590c-11eb-9def-b03f1c0656d4.png)

**Comment by enovikov11** [comment]
пока админ проходит тест, нельзя ответить на вопросы на которые он не ответил

while the admin is passing the test, it is impossible to answer the questions that he did not answer

**Comment by TokenStyle** [comment]
Хорошо, понятно. Также я получил сообщение, спасибо за ответ!

OK, understood. Also I got the message, thanks for the reply!

![image](https://user-images.githubusercontent.com/56667933/104848089-94c02780-590d-11eb-8989-26852ebfb608.png)
